services:
  - type: web
    name: flask-react-app
    env: python
    buildCommand: |
      # Build frontend
      cd frontend
      npm install
      npm run build
      # Install backend dependencies
      cd ../backend
      pip install -r requirements.txt
    startCommand: cd backend && gunicorn --config gunicorn.conf.py app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: VITE_API_URL
        value: https://threed-viewer-309u.onrender.com
      - key: RENDER
        value: 'true'
      value:
    healthCheckPath: /health
    buildFilter:
      paths:
        - frontend/**
        - backend/**
